name: form_handler
description: "A new Flutter package project."
version: 0.0.2
repository: https://github.com/topperspal/flutter_form_handler

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
